plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.responseinterceptor'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.responseinterceptor"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    // 使用正确的版本号
    compileOnly 'io.github.libxposed:api:102.0.0'
    compileOnly 'com.squareup.okhttp3:okhttp:4.12.0'
}
